name: flutter_base
description: A base Flutter project.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  auto_route: ^10.1.0+1
  flutter_config:
    git:
      url: https://github.com/cogivn/flutter_config.git
      ref: master
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable:
    git:
      url: https://github.com/cogivn/injectable.git
      path: injectable
      ref: develop
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  loggy: ^2.0.3
  package_info_plus: ^8.3.0
  dartz: ^0.10.1
  uuid: ^4.5.1
  enum_annotation: ^0.0.4
  rx_shared_preferences: ^4.0.0
  streaming_shared_preferences: ^2.0.0
  dartx: ^1.2.0
  result_dart: ^2.1.1
  retrofit: ^4.5.0
  talker_flutter: ^4.9.2
  talker_dio_logger: ^4.9.2
  talker_riverpod_logger: ^4.9.2
  faker_dart: ^0.2.2
  webview_flutter: ^4.13.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  sizing: ^1.1.2
  flutter_html: ^3.0.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.5.4
  mocktail: ^1.0.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  auto_route_generator: ^10.2.3
  flutter_gen_runner: ^5.10.0
  intl_utils: ^2.8.11
  enum_generator: ^1.1.4
  injectable_generator:
    git:
      url: https://github.com/cogivn/injectable.git
      path: injectable_generator
      ref: develop
  flutter_launcher_icons: ^0.14.4
  retrofit_generator: ^9.2.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    rive: false

  assets:
    enabled: true
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

flutter_intl:
  enabled: true
  main_locale: "en"
  arb_dir: assets/l10n
