name: flutter_base
description: A base Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  asuka: ^2.0.0
  auto_route: ^7.4.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_config: ^2.0.2
  flutter_loggy: ^2.0.1
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.0
  dio: ^5.0.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  loggy: ^2.0.1
  meta: ^1.7.0
  package_info_plus: ^4.0.2
  rxdart: ^0.27.4
  dartz: ^0.10.1
  uuid: ^3.0.6
  stack_trace: ^1.10.0
  injectable: ^2.1.0
  rx_shared_preferences: ^3.0.0
  collection: ^1.17.0
  dartx: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  freezed: ^2.1.0
  json_serializable: ^6.4.0
  auto_route_generator: ^7.1.1
  flutter_gen_runner: ^5.3.0
  intl_utils: ^2.7.0
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: 'zh_Hant'
  arb_dir: assets/l10n
