name: flutter_base
description: A base Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  asuka: ^2.0.1+3
  auto_route: ^5.0.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_config_plus: ^1.1.1
  flutter_loggy: ^2.0.1
  flutter_svg: ^2.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  dio: ^5.0.0
  get_it: ^7.2.0
  injectable: ^2.0.1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  loggy: ^2.0.1
  meta: ^1.7.0
  package_info_plus: ^3.0.3
  rxdart: ^0.27.4
  dartz: ^0.10.1
  uuid: ^3.0.7
  stack_trace: ^1.10.0
  enum_annotation: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.2.0
  intl_utils: ^2.8.1
  enum_generator: ^1.0.8
  injectable_generator: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    output:
      enabled: true
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: 'en'
  arb_dir: assets/l10n
